-- MySQL Script generated by MySQL Workbench
-- qua 10 fev 2021 18:30:37 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wjcrypto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wjcrypto` ;

-- -----------------------------------------------------
-- Schema wjcrypto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wjcrypto` DEFAULT CHARACTER SET utf8 ;
USE `wjcrypto` ;

-- -----------------------------------------------------
-- Table `wjcrypto`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wjcrypto`.`user` ;

CREATE TABLE IF NOT EXISTS `wjcrypto`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_business_customer` TINYINT(1) NOT NULL DEFAULT 0,
  `taxvat` VARCHAR(15) NOT NULL,
  `person_document_number` VARCHAR(45) NOT NULL,
  `corporate_name` VARCHAR(45) NULL,
  `relevant_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wjcrypto`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wjcrypto`.`account` ;

CREATE TABLE IF NOT EXISTS `wjcrypto`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 0,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wjcrypto`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wjcrypto`.`application_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wjcrypto`.`application_log` ;

CREATE TABLE IF NOT EXISTS `wjcrypto`.`application_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `account_id` INT(11) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `session_identifier` VARCHAR(45) NULL DEFAULT NULL,
  `device` VARCHAR(45) NULL DEFAULT NULL,
  `message` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_log_account1_idx` (`account_id` ASC),
  INDEX `fk_application_log_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_account_log_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `wjcrypto`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_application_log_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wjcrypto`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wjcrypto`.`transaction_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wjcrypto`.`transaction_type` ;

CREATE TABLE IF NOT EXISTS `wjcrypto`.`transaction_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wjcrypto`.`account_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wjcrypto`.`account_transaction` ;

CREATE TABLE IF NOT EXISTS `wjcrypto`.`account_transaction` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `transaction_type_id` INT(11) NOT NULL,
  `origin_account_id` INT(11) NOT NULL,
  `target_account_id` INT(11) NULL DEFAULT NULL,
  `date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_transaction_account1_idx` (`origin_account_id` ASC),
  INDEX `fk_account_transaction_account2_idx` (`target_account_id` ASC),
  INDEX `fk_account_transaction_transaction_type1_idx` (`transaction_type_id` ASC),
  CONSTRAINT `fk_account_transaction_account1`
    FOREIGN KEY (`origin_account_id`)
    REFERENCES `wjcrypto`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_transaction_account2`
    FOREIGN KEY (`target_account_id`)
    REFERENCES `wjcrypto`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_transaction_transaction_type1`
    FOREIGN KEY (`transaction_type_id`)
    REFERENCES `wjcrypto`.`transaction_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wjcrypto`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wjcrypto`.`address` ;

CREATE TABLE IF NOT EXISTS `wjcrypto`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `street_number` VARCHAR(45) NOT NULL,
  `street_number_adition` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_address_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wjcrypto`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
